name: Docker Image CI

on:
  push:
    branches: [ "main", "ver0.0.2"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag DataFrameJ4:$(date +%s)
