name: Docker Image CI

on:
  push:
    branches: [ "main", "ver0.0.2"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dataframe4j:$(date +%s)
