name: Publish to Sonatype

on:
  push:
    branches: [ "ver0.0.2" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Generate Source
        run: mvn source:jar

      - name: Deploy to Sonatype
        run: mvn deploy --settings .github/settings.xml

        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
