name: Publish Docker Image

on:
  push:
    branches: [ "ver0.0.2" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t joopererer/dataframe4j_fake:latest .
          docker push joopererer/dataframe4j_fake:latest

      - name: Login to GitHub Package
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Tag and push Docker image to GitHub Package
        run: |
          docker tag joopererer/dataframe4j_fake:latest docker.pkg.github.com/joopererer/DataFrame4J_fake/dataframe4j_fake:latest
          docker push docker.pkg.github.com/joopererer/DataFrame4J_fake/dataframe4j_fake:latest
